server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/student/**
        - id: teacher-service
          uri: lb://teacher-service
          predicates:
            - Path=/teacher/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**