server:
  port: 8081
  servlet:
    context-path: /student # 访问本服务所有的请求都要加上/student前缀（用于gateway断言）

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gpms?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: student-service
  cloud:
    nacos:
      server-addr: localhost:8848
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB


mybatis:
  type-aliases-package: com.wt.gpms.student.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换
