server:
  port: 8082
  servlet:
    context-path: /teacher # 访问本服务所有的请求都要加上/teacher前缀（用于gateway断言）
    session:
      tracking-modes: COOKIE

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gpms?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: teacher-service
  cloud:
    nacos:
      server-addr: localhost:8848

mybatis:
  type-aliases-package: com.wt.gpms.teacher.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换